## YAML Template.
AppBundle\Entity\Campaign:
    type: entity
    table: campaign
    id:
        id:
            type: integer
            generator: {strategy : AUTO}
    fields:
        name:
        startDate:
        finishDate:
        totalTons:
        costDetail:
        tonsPerHas:
        status:
        plot:    
            
